name: daily

on: [push, pull_request]

jobs:
  daily:
    timeout-minutes: 10
    name: RG Cron ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
          - { os: ubuntu  , ruby: head  }
          - { os: macos   , ruby: head  }
          - { os: windows , ruby: mingw }
          - { os: windows , ruby: mswin }
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Test rubygems
        run:  |
          gem install builder -N
          rake test
