name: install-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  install_rubygems_windows:
    name: Install Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2022
    env:
      JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "3.1", value: 3.1.2 }
          - { name: jruby-9.3, value: jruby-9.3.4.0 }
    steps:
      - uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Setup java
        uses: actions/setup-java@v3.5.0
        with:
          distribution: temurin
          java-version: 18.0.0
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Install rubygems
        run: ruby setup.rb
        shell: bash
      - name: Check installation didn't modify any source controlled files
        run: git diff --exit-code
        shell: bash
      - name: Check we can install a Gemfile with git sources
        run: bundle init && bundle add fileutils --git https://github.com/ruby/fileutils
        shell: bash

    timeout-minutes: 10
